apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-deployment
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: pass123
            - name: POSTGRES_USER
              value: dbuser
            - name: POSTGRES_DB
              value: appdb
          image: postgres:16
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-pvc-volume
            - mountPath: /docker-entrypoint-initdb.d
              name: userssql-initdb
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: db-pvc-volume
          persistentVolumeClaim:
            claimName: db-pvc-volume
        - name: userssql-initdb
          configMap:
            name: userssql-initdb-config