apiVersion: v1
kind: Service
metadata:
  labels:
    app: vta
  name: vta
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: vta
  selector:
    app: vta
  type: ClusterIP